[PrimaryGenerator]
# If PythonGenerator terminates before reaching NumEvents, then subsequent
# generated events are aborted

# Generates electron/positron pairs to illustrate magnetic design
PythonGenerator = 'cpt.pattern_spray'
NumEvents = 100

# Generates gammas along z-axis to demonstrate Compton performance at 20 MeV
# PythonGenerator = 'cpt.repetitive_spray'
# PythonGeneratorArgs = ['gamma', '20*MeV', '0*mm', '0*mm', '-10*mm']
# NumEvents = 10000

[Geometry.World]
Type = 'G4Box'
pX = 2000.0   # X half-length (unit=mm)
pY = 2000.0   # Y half-length (unit=mm)
pZ = 2400.0   # Z half-length (unit=mm)
Material = 'G4_He'
Translation = [0, 0, 0]
Rotation = [0, 0, 0]
Color = [0.0, 0.2, 1.0, 0.2]   # converter color (r g b a)
Visible = false

[Geometry.World.Converter]
Type = 'G4Box'
pX = 2.0
pY = 40.0
pZ = 2.0
Material = 'G4_Li'
Translation = [0.0, 0.0, -2.0]
Rotation = [0, 0, 0]
Color = [1.0, 1.0, 1.0, 1.0]   # converter color (r g b a)

[Geometry.World.ComptonPoleTopRight]
Type = 'CadMesh'
File = '../../cad/cpt.stl'
SolidName = 'cpt_pole:top_right'
Material = 'G4_Fe'
Color = [1.0, 1.0, 1.0, 1.0]

[Geometry.World.ComptonPoleBottomRight]
Type = 'CadMesh'
File = '../../cad/cpt.stl'
SolidName = 'cpt_pole:bottom_right'
Material = 'G4_Fe'
Color = [1.0, 1.0, 1.0, 1.0]

[Geometry.World.ComptonPoleTopLeft]
Type = 'CadMesh'
File = '../../cad/cpt.stl'
SolidName = 'cpt_pole:top_left'
Material = 'G4_Fe'
Color = [1.0, 1.0, 1.0, 1.0]

[Geometry.World.ComptonPoleBottomLeft]
Type = 'CadMesh'
File = '../../cad/cpt.stl'
SolidName = 'cpt_pole:bottom_left'
Material = 'G4_Fe'
Color = [1.0, 1.0, 1.0, 1.0]

[Geometry.World.ComptonYokeRight]
Type = 'CadMesh'
File = '../../cad/cpt.stl'
SolidName = 'cpt_yoke:right'
Material = 'G4_Fe'
Color = [1.0, 1.0, 1.0, 1.0]

[Geometry.World.ComptonYokeLeft]
Type = 'CadMesh'
File = '../../cad/cpt.stl'
SolidName = 'cpt_yoke:left'
Material = 'G4_Fe'
Color = [1.0, 1.0, 1.0, 1.0]

[Geometry.World.PairYoke]
Type = 'CadMesh'
File = '../../cad/cpt.stl'
SolidName = 'sf_yoke:yoke'
Material = 'G4_Fe'
Color = [1.0, 1.0, 1.0, 1.0]

[Geometry.World.PairPoleBottom]
Type = 'CadMesh'
File = '../../cad/cpt.stl'
SolidName = 'sf_pole:bottom'
Material = 'G4_Fe'
Color = [1.0, 1.0, 1.0, 1.0]

[Geometry.World.PairPoleTop]
Type = 'CadMesh'
File = '../../cad/cpt.stl'
SolidName = 'sf_pole:top'
Material = 'G4_Fe'
Color = [1.0, 1.0, 1.0, 1.0]

[Geometry.World.Coils]
Type = 'CadMesh'
File = '../../cad/cpt-coils.stl'
Material = 'G4_Cu'
Color = [0.72, 0.45, 0.20, 1.0]   # converter color (r g b a)

[Geometry.World.ComptonScintRight]
Type = 'CadMesh'
File = '../../cad/cpt.stl'
SolidName = 'cpt_scint:right'
Material = 'G4_CESIUM_IODIDE'
Color = [0.082, 0.722, 0.859, 0.3]   # converter color (r g b a)

[Geometry.World.ComptonScintLeft]
Type = 'CadMesh'
File = '../../cad/cpt.stl'
SolidName = 'cpt_scint:left'
Material = 'G4_CESIUM_IODIDE'
Color = [0.082, 0.722, 0.859, 0.3]   # converter color (r g b a)

[Geometry.World.PairScintRight]
Type = 'CadMesh'
File = '../../cad/cpt.stl'
SolidName = 'sf_scint:right'
Material = 'G4_CESIUM_IODIDE'
Color = [0.082, 0.722, 0.859, 0.3]   # converter color (r g b a)

[Geometry.World.PairScintLeft]
Type = 'CadMesh'
File = '../../cad/cpt.stl'
SolidName = 'sf_scint:left'
Material = 'G4_CESIUM_IODIDE'
Color = [0.082, 0.722, 0.859, 0.3]   # converter color (r g b a)

[Fields.Cpt]
Type = 'ImportedMagneticField'
File = '../../field/B-field-5mm.h5'

[Detectors.ComptonScintRight]
Type = 'SimpleDepositionSD'
Volumes = ['World.ComptonScintRight']
File = 'edep-cr.h5'

[Detectors.ComptonScintLeft]
Type = 'SimpleDepositionSD'
Volumes = ['World.ComptonScintLeft']
File = 'edep-cl.h5'

[Detectors.PairScintRight]
Type = 'SimpleDepositionSD'
Volumes = ['World.PairScintRight']
File = 'edep-pr.h5'

[Detectors.PairScintLeft]
Type = 'SimpleDepositionSD'
Volumes = ['World.PairScintLeft']
File = 'edep-pl.h5'
