[Files]
Input = 'out/reduced-edep.h5'
RunIndex = [0,0,0]
Output = 'deposition.pdf'
GammasPerShot = 1e9

[Annotation]
Text = ['Xenon', '$E_\gamma$ = 30 MeV', '$y_0$ = 0 mm', '$d_{Li}$ = 0.5 mm']
loc = [0.60, 0.70]
ShotLabel = '$10^9$ gammas'
# ShotLabel = 'shot'

[MagnetProfile]
vpole_a1 = 0.1
d0 = 50.0
d1 = 60.0
c1 = 250        # b0 + b1 - c0 = 10 + 300 - 60 = 250
